# Extra library for the main sample project
# Only shares same .config

UwUMaker-dirs-y += lib
UwUMaker-c-flags-y += -fvisibility=hidden

UwUMaker-is-executable := n

# Project name excluding extension and prefix
UwUMaker-name := ExtraLibStatic

