
UwUMaker-dirs-y += app

# Global flags (applies recursively)
UwUMaker-c-flags			+= -g -DIM_FROM_ROOT_MAKEFILE=1
UwUMaker-as-flags			+= -g -DIM_ASSEMBLER_FROM_ROOT_MAKEFILE=1

# Linker flags for final Executable
# (applies recursively but useless as
# each directory only generates
# combined .o file)
UwUMaker-linker-flags += -L/usr/lib -lpthread -lm -lc


