[Project]
name = "Sample"
type = "executable"

# If CONFIG_* is y then for non array
# its overwritten
name-CONFIG_SWAP_NAME = "Swapped"

# Subdir section
[Subdir]
sources-c = [ "main.c" ]

# If CONFIG_* is y then for arrays
# its appended
sources-c-CONFIG_COMPILE_EXTRA = [ "common.c" ]

