[Project]
name = "Sample"
type = "exe"

# Subdir section
[Subdir]
c-sources = [ "main.c" ]

# Options in any table named CONFIG_* are only applied
# if CONFIG_* is y (note for CONFIG_* set to 'm', 
# CONFIG_*_MODULE is set to 'y')
[Subdir.CONFIG_COMMON]
c-sources = [ "common.c" ]


