# final product

SHARED_LIB_EXTENSION := .so
STATIC_LIB_EXTENSION := .a
EXECUTABLE_EXTENSION :=

ifeq ($(FINAL_PRODUCT_TYPE),y)
FINAL_PRODUCT	:= $(OBJS_DIR)/$(PROJECT_NAME)$(EXECUTABLE_EXTENSION)
endif

ifeq ($(FINAL_PRODUCT_TYPE),m)
FINAL_PRODUCT	:= $(OBJS_DIR)/lib$(PROJECT_NAME)$(SHARED_LIB_EXTENSION)
endif

ifeq ($(FINAL_PRODUCT_TYPE),n)
FINAL_PRODUCT	:= $(OBJS_DIR)/lib$(PROJECT_NAME)$(STATIC_LIB_EXTENSION)
endif

